### ISSUE TITLE
input_size not defined in Convert_ONNX()

### ISSUE THREAD

**Issue by arisha07** [MicrosoftDocs/windows-ai-docs#62]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b236fa85-23be-f5ec-5c5f-332937187f04
* Version Independent ID: 781552b8-a796-a963-05d3-ed98f509dbd4
* Content: [Convert your PyTorch model to ONNX](https://docs.microsoft.com/en-us/windows/ai/windows-ml/tutorials/pytorch-convert-model)
* Content Source: [docs/windows-ml/tutorials/pytorch-convert-model.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/tutorials/pytorch-convert-model.md)
* Product: **machine-learning**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by anrahman4** [comment]
I have found a solution:

Replace dummy_input = torch.randn(1, input_size, requires_grad=True) with dummy_input = torch.randn(1, 3, 32, 32, requires_grad=True)

torch.randn is used to create a randomized tensor to feed into the model. The first parameter is the batch size, it is set to 1 here but I believe it can be set to other values as well. The second parameter is number of channels. In this tutorial, the first convolutional neural network layer has 3 channels, so it is expecting an input tensor to have the same value, and thus it is set to 3.

Lastly, the last two parameters are height and width. Since it is using images in the CIFAR10 dataset, the height and width are both 32.

If you then run the Convert_ONNX function, you should get the proper output.

**Comment by QuinnRadich** [comment]
My apologies for letting this issue sit unassigned for such a long time.

I believe this problem has been resolved. Moreover, the tutorial in question is likely to see further updates soon, along with many other docs in this repo.
