### ISSUE TITLE
NVIDIA CUDA drivers for WSL

### ISSUE THREAD

**Issue by adamgell** [MicrosoftDocs/windows-ai-docs#73]
Finding the Nvidia drivers off this page is difficult. Can a direct link be provided? 

```Download and install the [NVIDIA CUDA enabled driver for WSL](https://www.nvidia.com/download/index.aspx) to use with your existing CUDA ML workflows.```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdfa117-e801-0df5-3c81-3151a97f431d
* Version Independent ID: ee755d20-17c2-3d18-0c5c-b9ed31135218
* Content: [Enable NVIDIA CUDA on WSL 2](https://docs.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl)
* Content Source: [docs/directml/gpu-cuda-in-wsl.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-cuda-in-wsl.md)
* Product: **machine-learning**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @adamgell.

In the topic, I've added a link to https://docs.nvidia.com/cuda/wsl-user-guide/index.html#installing-nvidia-drivers, since that describes more about the kind of driver to install.

As for a direct link, I don't think there is one. Even Nvidia's page here (https://developer.nvidia.com/cuda/wsl) links directly to the drop-downs (see the "Get CUDA Driver" button on that page).

-Steve

**Comment by adamgell** [comment]
https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_local
