### ISSUE TITLE
Is WSL2 on windows server 2022 21H2 available for gpu access?

### ISSUE THREAD

**Issue by joshuia** [MicrosoftDocs/windows-ai-docs#83]
Env: win serve r2022 (21H2) + WSL2（5.4） + ubuntu 20.04 + cuda11.0

When I use "nvidia-smi" , it shows:

Failed to initialize NVML: GPU access blocked by the operating system
Failed to properly shut down NVML: GPU access blocked by the operating system

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdfa117-e801-0df5-3c81-3151a97f431d
* Version Independent ID: ee755d20-17c2-3d18-0c5c-b9ed31135218
* Content: [Enable NVIDIA CUDA on WSL 2](https://docs.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl)
* Content Source: [docs/directml/gpu-cuda-in-wsl.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-cuda-in-wsl.md)
* Product: **machine-learning**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @joshuia, and thanks for filing this issue.

I believe that there's nothing incorrect in this specific topic, so this doesn't appear to be a docs issue.

You could try sharing feedback on NVIDIA's support via their [Community forum for CUDA on WSL](https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-on-windows-subsystem-for-linux/303).

The feedback channel you're using here (**Submit and view feedback for** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete.

For questions (or requests for help) regarding the way a Microsoft software product behaves, one option is to click **Submit and view feedback for** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Thanks!
-Steve
